name = "kimpure/asciitable"
version = "0.3.8"
description = "try outputting in ascii"
authors = ["kimpure (sunwoo)"]
repository = "https://github.com/kimpure/asciitable-luau"
license = "MIT"
includes = [ "src/**", "pesde.toml", "LICENCE.md", "README.md" ]

[target]
environment = "luau"
lib = "src/lib.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.1"

