return {
    table_chars = {
        middleMiddle = '─',
        rowMiddle = '┼',
        topRight = '┐',
        topLeft = '┌',  
        leftMiddle = '├',
        topMiddle = '┬',
        bottomRight = '┘',
        bottomLeft = '└',
        bottomMiddle = '┴',
        rightMiddle = '┤',
        left = '│ ',
        right = ' │',
        middle = '│'
    },
    
    tree_chars = {
        middleMiddle = '─',
        rowMiddle = '┼',
        topRight = '┐',
        topLeft = '┌',
        leftMiddle = '├',
        topMiddle = '┬',
        bottomRight = '┘',
        bottomLeft = '└',
        bottomMiddle = '┴',
        rightMiddle = '┤',
        left = '│ ',
        right = ' │',
        middle = '│'
    },

    table_round_chars = {
        middleMiddle = '─',
        rowMiddle = '┼',
        topRight = '╮',
        topLeft = '╭',
        leftMiddle = '├',
        topMiddle = '┬',
        bottomRight = '╯',
        bottomLeft = '╰',
        bottomMiddle = '┴',
        rightMiddle = '┤',
        left = '│ ',
        right = ' │',
        middle = '│'
    },

    tree_round_chars = {
        middleMiddle = '─',
        rowMiddle = '┼',
        topRight = '╮',
        topLeft = '╭',
        leftMiddle = '├',
        topMiddle = '┬',
        bottomRight = '╯',
        bottomLeft = '╰',
        bottomMiddle = '┴',
        rightMiddle = '┤',
        left = '│ ',
        right = ' │',
        middle = '│'
    },
}